<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from 'vue';
import { onBeforeRouteLeave } from 'vue-router';
import { ApiError, command, errorMessage, today } from '@worktime/api-client';
import ModalShell from '../../shared/ModalShell.vue';
const props=defineProps<{kind:'users'|'managers';userIds:string[];departments:{id:string;name:string}[]}>();const emit=defineEmits<{busy:[value:boolean];close:[];done:[]}>();
interface Preview {expectedFingerprint:string;canApply:boolean;errors:string[];rows?:{userId:string;employeeNo:string;name:string;fromDepartmentName:string;toDepartmentName:string;fromLevel:string;toLevel:string;affectedDayCount:number;approvedRevisionCount:number}[];users?:{userId:string;employeeNo:string;name:string}[];departmentName?:string}
const busy=ref(false),error=ref(''),department=ref(''),level=ref(''),title=ref('DEPUTY'),from=ref(today()),to=ref(''),reason=ref(''),preview=ref<Preview>();
const levelName=(v:string)=>({JUNIOR:'初级',MIDDLE:'中级',SENIOR:'高级'} as Record<string,string>)[v]??v;
watch(busy,v=>emit('busy',v));watch([department,level,title,from,to,reason],()=>preview.value=undefined);
function body(){return props.kind==='users'?{userIds:props.userIds,departmentId:department.value||null,level:level.value||null,effectiveFrom:from.value,reason:reason.value}:{userIds:props.userIds,departmentId:department.value,title:title.value,effectiveFrom:from.value,effectiveTo:to.value||null,reason:reason.value};}
function path(){return props.kind==='users'?'/master/users/batch':'/master/department-managers/batch';}
async function inspect(){busy.value=true;error.value='';try{preview.value=await command<Preview>(path()+'/preview',body());}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
async function apply(){if(!preview.value?.canApply)return;busy.value=true;error.value='';try{await command(path()+'/apply',{...body(),expectedFingerprint:preview.value.expectedFingerprint});emit('done');}catch(e){error.value=errorMessage(e);if(e instanceof ApiError&&e.status===409)preview.value=undefined;}finally{busy.value=false;}}
function close(){if(!busy.value&&(!reason.value||window.confirm('调整方案尚未应用，确定关闭？')))emit('close');}
onBeforeRouteLeave(()=>!busy.value&&(!reason.value||window.confirm('批量方案尚未应用，确定离开？')));onBeforeUnmount(()=>emit('busy',false));
</script>
<template><ModalShell :busy="busy" @close="close"><section class="workflow-page workflow-dialog" role="dialog" aria-modal="true" aria-label="批量人员方案"><h2>{{ kind==='users'?'批量调整部门 / 职级':'批量登记负责人任职' }}</h2><p>已选择 {{ userIds.length }} 人。同一批次全部成功或回滚，原工号、企微身份与已有角色范围保留。</p><form @submit.prevent="inspect"><label>{{ kind==='users'?'目标部门（不选则保留）':'任职部门' }}<select v-model="department" aria-label="目标部门" :required="kind==='managers'" :disabled="busy"><option value="">{{ kind==='users'?'保持各人原部门':'选择部门' }}</option><option v-for="d in departments" :key="d.id" :value="d.id">{{ d.name }}</option></select></label><label v-if="kind==='users'">目标职级<select v-model="level" aria-label="目标职级" :disabled="busy"><option value="">保持各人原职级</option><option value="JUNIOR">初级</option><option value="MIDDLE">中级</option><option value="SENIOR">高级</option></select></label><label v-else>统一职务<select v-model="title" aria-label="统一职务" :disabled="busy"><option value="HEAD">正职</option><option value="DEPUTY">副职</option></select></label><label>生效日期<input v-model="from" type="date" :max="kind==='users'?today():undefined" required :disabled="busy" /></label><label v-if="kind==='managers'">结束日期（不含）<input v-model="to" type="date" :min="from" :disabled="busy" /></label><label>业务核实理由<textarea v-model="reason" rows="3" required maxlength="1000" :disabled="busy" /></label><p v-if="error" class="workflow-error" role="alert">{{ error }}</p><section v-if="preview" class="workflow-panel"><h3>预览影响</h3><p v-for="line in preview.errors" :key="line" class="workflow-error">{{ line }}</p><div v-if="preview.rows" class="workflow-table-wrap"><table class="workflow-table"><thead><tr><th>人员</th><th>部门</th><th>职级</th><th>影响日数</th><th>已确认版本</th></tr></thead><tbody><tr v-for="u in preview.rows" :key="u.userId"><td>{{ u.name }} / {{ u.employeeNo }}</td><td>{{ u.fromDepartmentName }} → {{ u.toDepartmentName }}</td><td>{{ levelName(u.fromLevel) }} → {{ levelName(u.toLevel) }}</td><td>{{ u.affectedDayCount }}</td><td>{{ u.approvedRevisionCount }}</td></tr></tbody></table></div><p v-if="preview.users">{{ preview.departmentName }} · {{ title==='HEAD'?'正职':'副职' }}：{{ preview.users.map(u=>`${u.name} / ${u.employeeNo}`).join('，') }}</p><p class="workflow-note">已有批准快照与封账历史受保护。预览后状态改变将要求重新核实。</p></section><div class="workflow-actions"><button type="button" :disabled="busy" @click="close">取消</button><button type="submit" :disabled="busy||userIds.length>50||(!department&&!level)">预览方案</button><button class="primary" type="button" :disabled="busy||!preview?.canApply" @click="apply">确认应用整批</button></div></form></section></ModalShell></template>
