<script setup lang="ts">
import ModalShell from '../../shared/ModalShell.vue';
import { inject, onBeforeUnmount, onMounted, ref, watch, type Ref } from 'vue';
import { onBeforeRouteLeave } from 'vue-router';
import { api, command, displayTime, errorMessage, request, today, type Department } from '@worktime/api-client';
interface Coverage{id:string;dataset:string;fromDate:string;toDate:string;departmentId:string|null;departmentName:string|null;state:string;note:string;verifiedBy:string;verifiedAt:string;importBatchId:string|null}
const busy=ref(false),error=ref(''),notice=ref(''),rows=ref<Coverage[]>([]),departments=ref<Department[]>([]),open=ref(false),form=ref({dataset:'TRIP',fromDate:today(),toDate:today(),departmentId:null as string|null,state:'PARTIAL',note:'',importBatchId:null as string|null});const sharedBusy=inject<Ref<boolean>>('operationBusy');watch(busy,v=>{if(sharedBusy)sharedBusy.value=v;});
async function load(){busy.value=true;error.value='';try{[rows.value,departments.value]=await Promise.all([request<Coverage[]>('/source-coverage'),api.list<Department>('departments')]);}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
async function save(){busy.value=true;error.value='';try{await command('/source-coverage',{...form.value,importBatchId:form.value.importBatchId||null});open.value=false;notice.value='来源覆盖核实已登记。';await load();}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
onMounted(load);onBeforeRouteLeave(()=>!busy.value&&(!open.value||!form.value.note||window.confirm('核实说明尚未提交，确定离开？')));onBeforeUnmount(()=>{if(sharedBusy)sharedBusy.value=false;});
</script>
<template><div class="workflow-page"><div class="workflow-head"><div><h1>来源覆盖核实</h1><p>确认资料覆盖的期间与组织范围，作为 OA 核对的依据。</p></div><button class="primary" :disabled="busy" @click="open=true;form.note=''">登记覆盖核实</button></div><p class="workflow-note">上传文件不会自动代表来源完整。仅经明确核实为完整的范围可用于判断“无单”；有错误批次不得标为完整。</p><p v-if="error" class="workflow-error" role="alert">{{ error }}</p><p v-if="notice" class="workflow-success">{{ notice }}</p><div v-if="!rows.length" class="workflow-empty">尚未登记来源覆盖；当前覆盖状态为未知。</div><article v-for="row in rows" :key="row.id" class="workflow-panel"><div class="workflow-between"><h2>{{ row.dataset==='TRIP'?'已审批出差':'已核实请假' }} · {{ row.departmentName||'全公司' }}</h2><span class="workflow-tag" :data-state="row.state">{{ ({COMPLETE:'完整覆盖',PARTIAL:'部分覆盖',FAILED:'核实失败'} as Record<string,string>)[row.state]??row.state }}</span></div><p>{{ row.fromDate }} 至 {{ row.toDate }} · {{ row.importBatchId?`关联批次 ${row.importBatchId}`:'无关联批次' }}</p><p>{{ row.note }}</p><small>{{ row.verifiedBy }} · {{ displayTime(row.verifiedAt) }}</small></article><ModalShell v-if="open" :busy="busy" @close="open=false"><div class="workflow-overlay"><section class="workflow-dialog" role="dialog" aria-modal="true" aria-label="登记来源覆盖"><h2>登记来源覆盖</h2><form @submit.prevent="save"><label>来源资料<select aria-label="来源资料" v-model="form.dataset" :disabled="busy"><option value="TRIP">已审批出差</option><option value="LEAVE">已核实请假</option></select></label><label>开始日期<input v-model="form.fromDate" type="date" required :disabled="busy" /></label><label>结束日期<input v-model="form.toDate" :min="form.fromDate" type="date" required :disabled="busy" /></label><label>组织范围<select aria-label="组织范围" v-model="form.departmentId" :disabled="busy"><option :value="null">全公司</option><option v-for="d in departments" :key="d.id" :value="d.id">{{ d.name }}</option></select></label><label>核实结论<select aria-label="核实结论" v-model="form.state" :disabled="busy"><option value="PARTIAL">部分覆盖</option><option value="COMPLETE">完整覆盖</option><option value="FAILED">核实失败</option></select></label><label>关联导入批次 ID<input v-model="form.importBatchId" placeholder="可留空" :disabled="busy" /></label><label>核实依据与说明<textarea v-model="form.note" required rows="4" maxlength="1000" :disabled="busy" /></label><p v-if="error" class="workflow-error">{{ error }}</p><div class="workflow-actions"><button type="button" :disabled="busy" @click="open=false">取消</button><button class="primary" type="submit" :disabled="busy">确认登记</button></div></form></section></div></ModalShell></div></template>
