<script setup lang="ts">
import ModalShell from '../../shared/ModalShell.vue';
import { inject, onBeforeUnmount, onMounted, ref, watch, type Ref } from 'vue';
import { onBeforeRouteLeave } from 'vue-router';
import { api, command, displayTime, errorMessage, request, today, type Department } from '@worktime/api-client';
interface Coverage{id:string;dataset:string;fromDate:string;toDate:string;departmentId:string|null;departmentName:string|null;state:string;note:string;verifiedBy:string;verifiedAt:string;importBatchId:string|null}
const busy=ref(false),error=ref(''),notice=ref(''),rows=ref<Coverage[]>([]),departments=ref<Department[]>([]),open=ref(false),form=ref({dataset:'TRIP',fromDate:today(),toDate:today(),departmentId:null as string|null,state:'PARTIAL',note:'',importBatchId:null as string|null});const sharedBusy=inject<Ref<boolean>>('operationBusy');watch(busy,v=>{if(sharedBusy)sharedBusy.value=v;});
async function load(){busy.value=true;error.value='';try{[rows.value,departments.value]=await Promise.all([request<Coverage[]>('/source-coverage'),api.list<Department>('departments')]);}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
async function save(){busy.value=true;error.value='';try{await command('/source-coverage',{...form.value,importBatchId:form.value.importBatchId||null});open.value=false;notice.value='数据完整性核查结果已保存。';await load();}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
onMounted(load);onBeforeRouteLeave(()=>!busy.value&&(!open.value||!form.value.note||window.confirm('核查说明尚未保存，确定离开？')));onBeforeUnmount(()=>{if(sharedBusy)sharedBusy.value=false;});
</script>
<template><div class="workflow-page"><div class="workflow-head"><div><h1>数据完整性核查</h1><p>核查指定日期和部门的出差、请假资料是否齐全，作为 OA 核对的依据。</p></div><button class="primary" :disabled="busy" @click="open=true;form.note=''">登记核查结果</button></div><p class="workflow-note">上传成功不代表数据已齐全。只有确认指定日期和部门的数据完整，才能判断“OA 无单”。导入批次仍有错误时，不能标为数据完整。</p><p v-if="error" class="workflow-error" role="alert">{{ error }}</p><p v-if="notice" class="workflow-success">{{ notice }}</p><div v-if="!rows.length" class="workflow-empty">尚无核查记录，暂不确定数据是否完整。</div><article v-for="row in rows" :key="row.id" class="workflow-panel"><div class="workflow-between"><h2>{{ row.dataset==='TRIP'?'已审批出差':'已核实请假' }} · {{ row.departmentName||'全公司' }}</h2><span class="workflow-tag" :data-state="row.state">{{ ({COMPLETE:'数据完整',PARTIAL:'数据不全',FAILED:'核查失败'} as Record<string,string>)[row.state]??row.state }}</span></div><p>{{ row.fromDate }} 至 {{ row.toDate }} · {{ row.importBatchId?`关联批次 ${row.importBatchId}`:'无关联批次' }}</p><p>{{ row.note }}</p><small>{{ row.verifiedBy }} · {{ displayTime(row.verifiedAt) }}</small></article><ModalShell v-if="open" :busy="busy" @close="open=false"><div class="workflow-overlay"><section class="workflow-dialog" role="dialog" aria-modal="true" aria-label="登记核查结果"><h2>登记核查结果</h2><form @submit.prevent="save"><label>资料类型<select aria-label="资料类型" v-model="form.dataset" :disabled="busy"><option value="TRIP">已审批出差</option><option value="LEAVE">已核实请假</option></select></label><label>开始日期<input v-model="form.fromDate" type="date" required :disabled="busy" /></label><label>结束日期<input v-model="form.toDate" :min="form.fromDate" type="date" required :disabled="busy" /></label><label>部门范围<select aria-label="部门范围" v-model="form.departmentId" :disabled="busy"><option :value="null">全公司</option><option v-for="d in departments" :key="d.id" :value="d.id">{{ d.name }}</option></select></label><label>核查结果<select aria-label="核查结果" v-model="form.state" :disabled="busy"><option value="PARTIAL">数据不全</option><option value="COMPLETE">数据完整</option><option value="FAILED">核查失败</option></select></label><label>关联导入批次编号<input v-model="form.importBatchId" placeholder="可留空" :disabled="busy" /></label><label>核查依据与说明<textarea v-model="form.note" required rows="4" maxlength="1000" :disabled="busy" /></label><p v-if="error" class="workflow-error">{{ error }}</p><div class="workflow-actions"><button type="button" :disabled="busy" @click="open=false">取消</button><button class="primary" type="submit" :disabled="busy">确认登记</button></div></form></section></div></ModalShell></div></template>
