ALTER TABLE time_entry_revision
  ADD submitted_at DATETIME(6) NULL,
  ADD approved_at DATETIME(6) NULL,
  ADD approved_by BIGINT NULL,
  ADD cost_amount DECIMAL(14,2) NULL,
  ADD cost_daily_rate DECIMAL(14,4) NULL,
  ADD cost_rate_id BIGINT NULL,
  ADD cost_level_history_id BIGINT NULL,
  ADD cost_level_code VARCHAR(20) NULL,
  ADD cost_policy_version VARCHAR(80) NULL,
  ADD owner_department_id BIGINT NULL,
  ADD dispute_open BOOLEAN NOT NULL DEFAULT FALSE,
  ADD correction_request_id BIGINT NULL,
  ADD CONSTRAINT fk_time_approved_by FOREIGN KEY (approved_by) REFERENCES app_user(id),
  ADD CONSTRAINT fk_time_cost_rate FOREIGN KEY (cost_rate_id) REFERENCES rate_card(id),
  ADD CONSTRAINT fk_time_cost_level FOREIGN KEY (cost_level_history_id) REFERENCES user_level_history(id),
  ADD CONSTRAINT fk_time_owner_department FOREIGN KEY (owner_department_id) REFERENCES department(id);
ALTER TABLE onsite_day_revision
  ADD submitted_at DATETIME(6) NULL,
  ADD approved_at DATETIME(6) NULL,
  ADD approved_by BIGINT NULL,
  ADD cost_amount DECIMAL(14,2) NULL,
  ADD cost_daily_rate DECIMAL(14,4) NULL,
  ADD cost_rate_id BIGINT NULL,
  ADD cost_policy_version VARCHAR(80) NULL,
  ADD owner_department_id BIGINT NULL,
  ADD dispute_open BOOLEAN NOT NULL DEFAULT FALSE,
  ADD correction_request_id BIGINT NULL,
  ADD CONSTRAINT fk_onsite_approved_by FOREIGN KEY (approved_by) REFERENCES app_user(id),
  ADD CONSTRAINT fk_onsite_cost_rate FOREIGN KEY (cost_rate_id) REFERENCES onsite_rate(id),
  ADD CONSTRAINT fk_onsite_owner_department FOREIGN KEY (owner_department_id) REFERENCES department(id);

CREATE TABLE approval_package (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT NOT NULL,
 week_start DATE NOT NULL,
 work_item_id BIGINT NOT NULL,
 approver_user_id BIGINT NOT NULL,
 default_approver_id BIGINT NULL,
 route_reason VARCHAR(500) NOT NULL,
 submit_deadline DATETIME(6) NOT NULL,
 approval_deadline DATETIME(6) NOT NULL,
 config_version_id VARCHAR(64) NOT NULL,
 row_version INT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 UNIQUE KEY uk_approval_package (user_id,week_start,work_item_id),
 KEY idx_package_pending (approver_user_id,approval_deadline),
 FOREIGN KEY (user_id) REFERENCES app_user(id),
 FOREIGN KEY (work_item_id) REFERENCES work_item(id),
 FOREIGN KEY (approver_user_id) REFERENCES app_user(id),
 FOREIGN KEY (default_approver_id) REFERENCES app_user(id),
 CHECK (user_id<>approver_user_id),
 CHECK (WEEKDAY(week_start)=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE approval_item (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 package_id BIGINT NOT NULL,
 time_revision_id BIGINT NULL,
 onsite_revision_id BIGINT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 submitted_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 submit_deadline DATETIME(6) NOT NULL,
 approval_deadline DATETIME(6) NOT NULL,
 handled_by BIGINT NULL,
 handled_at DATETIME(6) NULL,
 reason VARCHAR(1000) NOT NULL DEFAULT '',
 UNIQUE KEY uk_approval_time_version (time_revision_id),
 UNIQUE KEY uk_approval_onsite_version (onsite_revision_id),
 KEY idx_approval_pending (package_id,status),
 FOREIGN KEY (package_id) REFERENCES approval_package(id),
 FOREIGN KEY (time_revision_id) REFERENCES time_entry_revision(id),
 FOREIGN KEY (onsite_revision_id) REFERENCES onsite_day_revision(id),
 FOREIGN KEY (handled_by) REFERENCES app_user(id),
 CHECK ((time_revision_id IS NULL)<>(onsite_revision_id IS NULL)),
 CHECK (status IN ('PENDING','APPROVED','REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE approval_transfer (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 package_id BIGINT NOT NULL,
 old_approver_id BIGINT NOT NULL,
 new_approver_id BIGINT NOT NULL,
 item_ids JSON NOT NULL,
 basis VARCHAR(1000) NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 created_by BIGINT NOT NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 FOREIGN KEY (package_id) REFERENCES approval_package(id),
 FOREIGN KEY (old_approver_id) REFERENCES app_user(id),
 FOREIGN KEY (new_approver_id) REFERENCES app_user(id),
 FOREIGN KEY (created_by) REFERENCES app_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE approval_designation (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT NOT NULL,
 work_item_id BIGINT NOT NULL,
 approver_user_id BIGINT NOT NULL,
 basis VARCHAR(1000) NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 created_by BIGINT NOT NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 UNIQUE KEY uk_designation (user_id,work_item_id),
 FOREIGN KEY (user_id) REFERENCES app_user(id),
 FOREIGN KEY (work_item_id) REFERENCES work_item(id),
 FOREIGN KEY (approver_user_id) REFERENCES app_user(id),
 FOREIGN KEY (created_by) REFERENCES app_user(id),
 CHECK (user_id<>approver_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE correction_request (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 kind VARCHAR(10) NOT NULL,
 record_id BIGINT NOT NULL,
 revision_id BIGINT NOT NULL,
 user_id BIGINT NOT NULL,
 work_date DATE NOT NULL,
 work_item_id BIGINT NOT NULL,
 requested_action VARCHAR(10) NOT NULL,
 requested_by BIGINT NOT NULL,
 approver_user_id BIGINT NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 state VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
 handled_by BIGINT NULL,
 handled_at DATETIME(6) NULL,
 handling_reason VARCHAR(1000) NULL,
 new_revision_id BIGINT NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 KEY idx_correction_current (kind,record_id,state),
 FOREIGN KEY (user_id) REFERENCES app_user(id),
 FOREIGN KEY (work_item_id) REFERENCES work_item(id),
 FOREIGN KEY (requested_by) REFERENCES app_user(id),
 FOREIGN KEY (approver_user_id) REFERENCES app_user(id),
 FOREIGN KEY (handled_by) REFERENCES app_user(id),
 CHECK (kind IN ('TIME','ONSITE')),
 CHECK (requested_action IN ('EDIT','CANCEL')),
 CHECK (state IN ('REQUESTED','APPROVED','DECLINED')),
 CHECK (user_id<>approver_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE time_entry_revision ADD CONSTRAINT fk_time_correction FOREIGN KEY (correction_request_id) REFERENCES correction_request(id);
ALTER TABLE onsite_day_revision ADD CONSTRAINT fk_onsite_correction FOREIGN KEY (correction_request_id) REFERENCES correction_request(id);
CREATE TABLE dispute_case (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 approval_item_id BIGINT NOT NULL,
 opened_by BIGINT NOT NULL,
 approver_user_id BIGINT NOT NULL,
 employee_statement TEXT NOT NULL,
 approver_statement TEXT NOT NULL,
 original_statement TEXT NOT NULL,
 state VARCHAR(20) NOT NULL DEFAULT 'OPEN',
 stage VARCHAR(20) NOT NULL DEFAULT 'COORDINATION',
 coordinator_id BIGINT NOT NULL,
 owner_department_id BIGINT NOT NULL,
 outcome VARCHAR(30) NULL,
 resolution_reason VARCHAR(1000) NULL,
 resolved_by BIGINT NULL,
 resolved_at DATETIME(6) NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 KEY idx_dispute_item (approval_item_id,state),
 KEY idx_dispute_coordinator (coordinator_id,state),
 FOREIGN KEY (approval_item_id) REFERENCES approval_item(id),
 FOREIGN KEY (opened_by) REFERENCES app_user(id),
 FOREIGN KEY (approver_user_id) REFERENCES app_user(id),
 FOREIGN KEY (coordinator_id) REFERENCES app_user(id),
 FOREIGN KEY (owner_department_id) REFERENCES department(id),
 FOREIGN KEY (resolved_by) REFERENCES app_user(id),
 CHECK (state IN ('OPEN','ESCALATED','RESOLVED')),
 CHECK (stage IN ('COORDINATION','RULING')),
 CHECK (outcome IS NULL OR outcome IN ('CONFIRM_FACTS','NEEDS_CORRECTION'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
