// Real per-item dispute and coordination, returning the test record to its confirmed factual state.
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { readFile, writeFile } from 'node:fs/promises';
import { chromium, expect } from '@playwright/test';
process.chdir(fileURLToPath(new URL('..',import.meta.url)));
const prior=JSON.parse(await readFile('local-verification/real-workflow.json','utf8')),browser=await chromium.launch();const evidence={mode:'real-local-api',packageId:prior.packageId,checks:[],pageErrors:[]};let active;
async function login(no,mobile=false){const p=await(await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1500,height:1000},locale:'zh-CN'})).newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>evidence.pageErrors.push(e.message));await p.goto(mobile?'http://127.0.0.1:5174/h5/':'http://127.0.0.1:5175/admin/');await p.locator(mobile?'input':'#employeeNo').fill(no);await p.getByRole('button',{name:mobile?'进入我的工时':'进入工作台',exact:true}).click();await expect(p.getByRole('button',{name:'保存草稿',exact:true})).toBeEnabled();return p;}
async function read(p,path){const r=await p.request.get(new URL('/api/v1'+path,p.url()).href);assert.equal(r.status(),200);return r.json();}
try{const employee=active=await login(prior.employeeNo,true);await employee.goto('http://127.0.0.1:5174/h5/approvals/'+prior.packageId);let dialog;const existing=(await read(employee,'/disputes')).find(d=>d.packageId===prior.packageId&&d.state==='OPEN');if(!existing){const item=employee.locator('article').filter({hasText:'完成设备调试并补充验收结论与交付清单'});await item.getByRole('button',{name:'发起争议协调'}).click();dialog=employee.getByRole('dialog',{name:'发起争议协调'});await dialog.getByLabel('事实说明 / 处理理由').fill('本地协调验证：请核实该条验收工作与原确认事实是否一致');await dialog.getByRole('button',{name:'确认提交'}).click();await expect(dialog).toHaveCount(0);}const all=await read(employee,'/disputes'),dispute=all.find(d=>d.packageId===prior.packageId&&d.state==='OPEN');assert.ok(dispute);evidence.disputeId=dispute.id;const detail=await read(employee,'/approval-packages/'+prior.packageId);assert.ok(detail.items.find(i=>i.id===dispute.approvalItemId).disputeOpen);
const manager=active=await login('ZD23412');await manager.goto('http://127.0.0.1:5175/admin/approvals');await manager.getByRole('button',{name:'争议协调',exact:true}).click();const card=manager.locator('article').filter({hasText:prior.employeeNo.slice(2)});const actualCard=card.first();await expect(actualCard).toBeVisible();await expect(actualCard.getByText('本地完整流程验证：完成设备调试并补充验收结论与交付清单',{exact:true})).toBeVisible();await actualCard.getByRole('button',{name:'记录结论'}).click();dialog=manager.getByRole('dialog',{name:'记录协调结论'});await dialog.getByLabel('结论',{exact:true}).selectOption('CONFIRM_FACTS');await dialog.getByLabel('事实说明 / 处理理由').fill('本地协调验证：核实原申报事实一致，保留原批准版本');await dialog.getByRole('button',{name:'确认提交'}).click();await expect(dialog).toHaveCount(0);await expect(actualCard.getByText('已解决',{exact:true})).toBeVisible();await manager.screenshot({path:'local-verification/real-admin-dispute-resolution.png',fullPage:true});const result=(await read(employee,'/disputes')).find(d=>d.id===dispute.id);assert.equal(result.state,'RESOLVED');assert.equal(result.outcome,'CONFIRM_FACTS');const final=await read(employee,'/approval-packages/'+prior.packageId);const resolved=final.items.find(i=>i.id===dispute.approvalItemId);assert.equal(resolved.disputeOpen,false);assert.equal(resolved.state,'APPROVED');evidence.checks.push('Employee raised per-item dispute; project owner department coordinator could read disputed facts without full package access, resolved to CONFIRM_FACTS, and original approval remained');assert.deepEqual(evidence.pageErrors,[]);console.log(JSON.stringify(evidence,null,2));}catch(error){evidence.failure=String(error);if(active)await active.screenshot({path:'local-verification/real-dispute-failure.png',fullPage:true});throw error;}finally{await writeFile('local-verification/real-dispute.json',JSON.stringify(evidence,null,2));await browser.close();}
