<script setup lang="ts">
import ModalShell from './ModalShell.vue';
import { computed, inject, onBeforeUnmount, onMounted, ref, watch, type Ref } from 'vue';
import { onBeforeRouteLeave, useRoute, useRouter } from 'vue-router';
import { api, displayTime, errorMessage, hours, monday, statusLabel, type ApprovalItem, type BatchResult, type CorrectionRequest, type Designation, type Dispute, type Me, type PackageDetail, type PackageSummary, type WorkItem } from '@worktime/api-client';
const route=useRoute(), router=useRouter(), me=inject<Ref<Me|undefined>>('me');
const sharedBusy=inject<Ref<boolean>>('operationBusy'), busy=ref(false), error=ref(''), notice=ref('');
const view=ref('pending'), rows=ref<PackageSummary[]>([]), detail=ref<PackageDetail>(), corrections=ref<CorrectionRequest[]>([]), disputes=ref<Dispute[]>([]), designations=ref<Designation[]>([]);
const selected=ref<string[]>([]), result=ref<BatchResult>(), users=ref<{id:string;name:string;employeeNo:string}[]>([]), objects=ref<WorkItem[]>([]);
const searchName=ref(''),filterWeek=ref(''),filterObject=ref('');
const objectsInRows=computed(()=>[...new Map(rows.value.map(p=>[p.workItemId,p.workItemName])).entries()]);
const visibleRows=computed(()=>rows.value.filter(p=>(!searchName.value||`${p.userName} ${p.employeeNo}`.includes(searchName.value))&&(!filterWeek.value||p.weekStart===monday(filterWeek.value))&&(!filterObject.value||p.workItemId===filterObject.value)));
const selectedCounts=computed(()=>({time:detail.value?.items.filter(i=>selected.value.includes(i.id)&&i.kind==='TIME').length??0,onsite:detail.value?.items.filter(i=>selected.value.includes(i.id)&&i.kind==='ONSITE').length??0}));
const modal=ref(''), target=ref<ApprovalItem|CorrectionRequest|Dispute>(), reason=ref(''), basis=ref(''), approver=ref(''), person=ref(''), object=ref(''), outcome=ref<'CONFIRM_FACTS'|'NEEDS_CORRECTION'>('CONFIRM_FACTS');
const eligible=computed(()=>detail.value?.items.filter(i=>i.canDecide).map(i=>i.id)??[]);
const canApproveSelected=computed(()=>selected.value.length>0&&detail.value?.items.filter(i=>selected.value.includes(i.id)).every(i=>i.canApprove??i.canDecide));
const canRejectSelected=computed(()=>selected.value.length>0&&detail.value?.items.filter(i=>selected.value.includes(i.id)).every(i=>i.canReject??i.canDecide));
const titles:Record<string,string>={APPROVE:'通过所选记录',REJECT:'驳回所选记录',EDIT:'申请更正',CANCEL:'申请取消申报',DISPUTE:'发起争议协调',COMMENT:'补充事实说明',RESOLVE:'记录协调结论',ESCALATE:'提交上级裁定',TRANSFER:'转交审批',TRANSFER_CORRECTION:'转交更正申请',CORRECTION_APPROVE:'同意更正申请',CORRECTION_DECLINE:'不同意更正申请',DESIGNATE:'设置公司指定的审批人'};
watch(busy,v=>{if(sharedBusy)sharedBusy.value=v;});
async function load(){busy.value=true;error.value='';try{if(route.params.id){detail.value=await api.package(String(route.params.id));selected.value=[];}else{detail.value=undefined;if(view.value==='corrections')corrections.value=await api.corrections();else if(view.value==='disputes')disputes.value=await api.disputes();else if(view.value==='designations')designations.value=await api.designations();else rows.value=await api.packages(view.value);}}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
async function changeView(value:string){if(busy.value)return;view.value=value;result.value=undefined;await load();}
async function open(kind:string,item?:ApprovalItem|CorrectionRequest|Dispute){if(busy.value)return;modal.value=kind;target.value=item;reason.value='';basis.value='';approver.value='';person.value='';object.value='';error.value='';if(['TRANSFER','TRANSFER_CORRECTION','DESIGNATE'].includes(kind)){busy.value=true;try{users.value=await api.list('users');objects.value=(await api.catalog()).workItems;}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}}
async function commit(){if(busy.value)return;if(modal.value!=='APPROVE'&&!reason.value.trim()){error.value='请填写事实说明或处理理由。';return;}busy.value=true;error.value='';result.value=undefined;try{const item=target.value;switch(modal.value){case 'APPROVE':case 'REJECT':result.value=await api.decide(detail.value!.package.id,detail.value!.package.version,selected.value,modal.value,reason.value);break;case 'EDIT':case 'CANCEL':{const t=item as ApprovalItem;await api.requestCorrection(t.kind,t.recordId,modal.value,reason.value);break;}case 'DISPUTE':await api.createDispute(item!.id,reason.value);break;case 'COMMENT':await api.commentDispute(item!.id,reason.value);break;case 'RESOLVE':case 'ESCALATE':await api.resolveDispute(item!.id,modal.value,modal.value==='RESOLVE'?outcome.value:null,reason.value);break;case 'CORRECTION_APPROVE':case 'CORRECTION_DECLINE':await api.decideCorrection(item!.id,modal.value==='CORRECTION_APPROVE'?'APPROVE':'DECLINE',reason.value);break;case 'TRANSFER':await api.transferPackage(detail.value!.package.id,{expectedVersion:detail.value!.package.version,newApproverId:approver.value,reason:reason.value,basis:basis.value});break;case 'TRANSFER_CORRECTION':await api.transferCorrection(item!.id,approver.value,reason.value,basis.value);break;case 'DESIGNATE':await api.saveDesignation({userId:person.value,workItemId:object.value,approverId:approver.value,reason:reason.value,basis:basis.value});break;}
notice.value='本次处理已保存。';modal.value='';await load();}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
onBeforeRouteLeave(()=>!busy.value&&(!modal.value||!reason.value||window.confirm('处理说明尚未提交，确定离开？')));
watch(()=>route.params.id,()=>void load());onMounted(load);onBeforeUnmount(()=>{if(sharedBusy)sharedBusy.value=false;});
</script>
<template>
<div class="workflow-page"><div class="workflow-head"><div><h1>审批中心</h1><p>确认工时、现场日和更正申请，处理填报争议。工时与现场日可分别审批。</p></div><button :disabled="busy" @click="load">刷新</button></div>
<p v-if="error" class="workflow-error" role="alert">{{ error }}</p><p v-if="notice" class="workflow-success" role="status">{{ notice }}</p>
<section v-if="result" class="workflow-panel" aria-live="polite"><strong>已处理 {{ result.succeeded.length }} 项 · 未处理 {{ result.failed.length }} 项 · 无需重复处理 {{ result.unchanged.length }} 项</strong><p v-for="(r,i) in [...result.succeeded,...result.failed,...result.unchanged]" :key="i">{{ r.date }} · {{ r.message }}</p></section>
<template v-if="!detail"><nav class="workflow-tabs" aria-label="审批分类"><button v-for="tab in [{id:'pending',name:'待我审批'},{id:'handled',name:'我已处理'},{id:'mine',name:'我提交的'},{id:'corrections',name:'更正申请'},{id:'disputes',name:'争议协调'},...(me?.canManage?[{id:'all',name:'审批转交'},{id:'designations',name:'指定审批人'}]:[])]" :key="tab.id" :class="{active:view===tab.id}" :disabled="busy" @click="changeView(tab.id)">{{ tab.name }}</button></nav>
<template v-if="!['corrections','disputes','designations'].includes(view)"><div class="workflow-filters"><label>姓名 / 工号<input v-model="searchName" placeholder="输入姓名或工号" :disabled="busy" /></label><label>选择一周内任意日期<input v-model="filterWeek" type="date" :disabled="busy" /></label><label>项目或事项<select aria-label="项目或事项" v-model="filterObject" :disabled="busy"><option value="">全部可见项目与事项</option><option v-for="[id,name] in objectsInRows" :key="id" :value="id">{{ name }}</option></select></label></div><div v-if="!visibleRows.length" class="workflow-empty">{{ busy?'正在加载审批单…':'当前分类没有审批单。' }}</div><button v-for="row in visibleRows" :key="row.id" class="workflow-panel package-card" :disabled="busy" @click="router.push(`/approvals/${row.id}`)"><div><strong>{{ row.userName }} <small>{{ row.employeeNo }}</small></strong><span>{{ row.pendingCount }} 项待处理</span></div><h2>{{ row.workItemName }}</h2><p v-if="row.redFlag||row.disputedCount||row.transferred" :class="row.redFlag ? 'workflow-error' : 'workflow-warning'">{{ row.redFlag?'有工时过长说明　':'' }}{{ row.disputedCount?`争议 ${row.disputedCount} 项　`:'' }}{{ row.transferred?'已转交审批':'' }}</p><p>{{ row.weekStart }} 所在周 · 实际工作 {{ hours(view==='pending'?(row.pendingWorkMinutes??row.workMinutes):row.workMinutes) }}h · 待安排工作 {{ hours(view==='pending'?(row.pendingIdleMinutes??row.idleMinutes):row.idleMinutes) }}h · 现场 {{ view==='pending'?(row.pendingOnsiteDays??row.onsiteDays):row.onsiteDays }} 天</p><small>审批人 {{ row.approverName }} · 截止 {{ displayTime(row.approvalDeadline) }}</small></button></template>
<template v-if="view==='corrections'"><p class="workflow-note">提交申请不会改变原记录。审批人同意后会生成更正或取消草稿，还需重新提交审批，获批后才生效。</p><div v-if="!corrections.length" class="workflow-empty">当前没有更正申请。</div><article v-for="item in corrections" :key="item.id" class="workflow-panel"><div class="workflow-between"><h2>{{ item.userName }} · {{ item.workItemName }}</h2><span class="workflow-tag" :data-state="item.state">{{ statusLabel(item.state) }}</span></div><p>{{ item.date }} · {{ statusLabel(item.action) }} · {{ item.kind==='ONSITE'?'现场日':'工时' }}</p><p>{{ item.reason }}</p><small>核实人：{{ item.approverName }}</small><div class="workflow-actions"><button v-if="item.canDecide" :disabled="busy" @click="open('CORRECTION_APPROVE',item)">同意申请</button><button v-if="item.canDecide" :disabled="busy" @click="open('CORRECTION_DECLINE',item)">不同意</button><button v-if="item.canTransfer" :disabled="busy" @click="open('TRANSFER_CORRECTION',item)">转交审批</button><RouterLink v-if="item.newRevisionId" :to="me?.canManage?'/time':'/'">返回工时填写</RouterLink></div></article></template>
<template v-if="view==='disputes'"><p class="workflow-note">争议只影响对应的记录版本。记录协调结论不会自动通过审批，也不会改变金额。</p><div v-if="!disputes.length" class="workflow-empty">当前没有你可以查看的争议。</div><article v-for="item in disputes" :key="item.id" class="workflow-panel"><div class="workflow-between"><h2>{{ item.userName }} · {{ item.workItemName }}</h2><span class="workflow-tag" :data-state="item.state">{{ statusLabel(item.state) }}</span></div><p>{{ item.date }} · {{ item.stage==='RULING'?'裁定人':'协调人' }}：{{ item.coordinatorName }}</p><p v-if="!item.kind" class="workflow-warning">尚未加载到原记录，请刷新后核实。当前无法记录结论或提交上级裁定。</p><div v-if="item.content" class="workflow-readonly"><strong>{{ item.kind==='ONSITE'?'现场日':`${item.hours}h` }} · {{ statusLabel(item.recordState??'') }}{{ item.action==='CANCEL'?' · 取消申报':'' }}</strong><p class="preserve-lines">{{ item.content }}</p><p v-if="item.redReason" class="workflow-error">工时过长说明：{{ item.redReason }}</p><small>发起 {{ displayTime(item.openedAt) }}{{ item.resolvedAt?` · 结案 ${displayTime(item.resolvedAt)}`:'' }}</small></div><dl><dt>员工说明</dt><dd>{{ item.employeeStatement||'尚未补充' }}</dd><dt>审批人说明</dt><dd>{{ item.approverStatement||'尚未补充' }}</dd><template v-if="item.resolutionReason"><dt>{{ statusLabel(item.outcome||'') }}</dt><dd>{{ item.resolutionReason }}</dd></template></dl><div class="workflow-actions"><button v-if="item.canComment" :disabled="busy" @click="open('COMMENT',item)">补充说明</button><button v-if="item.canResolve" :disabled="busy||!item.kind" @click="open('RESOLVE',item)">记录结论</button><button v-if="item.canEscalate" :disabled="busy||!item.kind" @click="open('ESCALATE',item)">提交上级裁定</button><button v-if="item.canComment || me?.id===item.userId" :disabled="busy" @click="router.push(`/approvals/${item.packageId}`)">查看关联记录</button></div></article></template>
<template v-if="view==='designations'"><p class="workflow-note">为指定人员填报的项目或事项设置审批人。审批人须在职且不能是填报人，并需填写公司的指定依据。</p><button class="primary" :disabled="busy" @click="open('DESIGNATE')">设置指定审批人</button><article v-for="item in designations" :key="item.id" class="workflow-panel"><h2>{{ item.userName }} · {{ item.workItemName }}</h2><p>指定 {{ item.approverName }}</p><p>{{ item.reason }} · {{ item.basis }}</p></article></template></template>
<template v-else><button :disabled="busy" @click="router.push('/approvals')">返回审批列表</button><section class="workflow-panel"><div class="workflow-between"><h2>{{ detail.package.userName }} · {{ detail.package.workItemName }}</h2><span>{{ detail.package.weekStart }} 所在周</span></div><p>审批人 {{ detail.package.approverName }} · {{ detail.package.routeReason }}</p><p>审批截止 {{ displayTime(detail.package.approvalDeadline) }}</p><p class="workflow-note">本周其他项目与事项的实际工作合计 {{ hours(detail.otherWorkMinutes) }}h，仅显示合计，不显示明细。</p><button v-if="detail.package.canTransfer" :disabled="busy" @click="open('TRANSFER')">转交审批</button></section>
<div v-if="eligible.length" class="workflow-actions"><label><input type="checkbox" :checked="selected.length===eligible.length" :disabled="busy" @change="selected=selected.length===eligible.length?[]:[...eligible]" /> 全选本审批单可处理的记录</label><button class="primary" :disabled="busy||!canApproveSelected" @click="open('APPROVE')">通过所选 {{ selected.length }} 项</button><button :disabled="busy||!canRejectSelected" @click="open('REJECT')">驳回所选</button></div>
<article v-for="item in detail.items" :key="item.id" class="workflow-panel"><div class="workflow-between"><label><input v-if="item.canDecide" v-model="selected" type="checkbox" :value="item.id" :disabled="busy" :aria-label="`选择 ${item.date} ${item.kind==='ONSITE'?'现场':'工时'}记录`" /> <strong>{{ item.date }} · {{ item.kind==='ONSITE'?'现场 1 天':`${item.hours}h` }}{{ item.action==='CANCEL'?' · 取消申报':'' }}</strong></label><span class="workflow-tag" :data-state="item.state">{{ statusLabel(item.state) }}{{ !item.current?' · 历史版本':'' }}</span></div><p class="preserve-lines">{{ item.content }}</p><p v-if="item.redReason" class="workflow-error">工时过长说明：{{ item.redReason }}</p><p v-if="item.dayWorkMinutes!==undefined" class="workflow-note">当日实际工作 {{ hours(item.dayWorkMinutes) }}h{{ item.projectWorkMinutes!==undefined?` · 本项目 ${hours(item.projectWorkMinutes)}h`: '' }}</p><p v-if="item.disputeOpen" class="workflow-warning">这条记录正在协调，暂不能通过；如需更正，由当前审批人驳回后修改。</p><p v-if="item.cost">{{ item.state==='PENDING'?'预估标准成本':'已确认标准成本' }} ¥{{ item.cost.amount }} · 标准 ¥{{ item.cost.dailyRate }}/日{{ item.cost.level?` · 职级 ${{JUNIOR:'初级',MIDDLE:'中级',SENIOR:'高级'}[item.cost.level as 'MIDDLE']??item.cost.level}`:'' }}</p><p v-if="item.kind==='ONSITE' && item.dayWorkMinutes!==undefined" :class="item.dayWorkMinutes>0&&(item.projectWorkMinutes??0)*2<item.dayWorkMinutes?'workflow-warning':'workflow-note'">当天本项目工时占比：{{ item.dayWorkMinutes>0?`${((item.projectWorkMinutes??0)/item.dayWorkMinutes*100).toFixed(1)}%`:'无实际工作工时，不适用' }}。当前占比含未审批工时，仅供核实参考；审批完成后，可在现场日明细中查看正式占比。{{ item.dayWorkMinutes>0&&(item.projectWorkMinutes??0)*2<item.dayWorkMinutes?'占比低于 50%，请核实现场情况；系统不会自动驳回。':'' }}</p><details v-if="item.cost"><summary>计价依据</summary><p>规则版本 {{ item.cost.policyVersion }} · 成本标准版本 {{ item.cost.rateId||'未提供' }}{{ item.cost.levelHistoryId?` · 职级历史 ${item.cost.levelHistoryId}`:'' }}</p></details><p v-if="item.costError" class="workflow-warning">暂时无法计算成本：{{ item.costError }}</p><p v-if="item.handledName">{{ item.handledName }} · {{ displayTime(item.handledAt) }} · {{ item.reason||'已确认' }}</p><div class="workflow-actions"><button v-if="item.canRequestCorrection" :disabled="busy" @click="open('EDIT',item)">申请更正</button><button v-if="item.canRequestCorrection" :disabled="busy" @click="open('CANCEL',item)">申请取消</button><button v-if="item.canDispute" :disabled="busy" @click="open('DISPUTE',item)">发起争议协调</button></div></article></template>
<ModalShell v-if="modal" :busy="busy" @close="modal=''"><div class="workflow-overlay" role="presentation"><section class="workflow-dialog" role="dialog" aria-modal="true" :aria-label="titles[modal]"><h2>{{ titles[modal] }}</h2><p v-if="['EDIT','CANCEL'].includes(modal)">先由原审批人核实申请。同意后生成更正或取消草稿，还需重新提交审批，获批后才生效。</p><p v-if="modal==='APPROVE'">将通过本审批单中所选的工时 {{ selectedCounts.time }} 项、现场 {{ selectedCounts.onsite }} 项。若部分记录无法处理，其余符合条件的记录仍会通过，请查看逐项结果。</p><form @submit.prevent="commit"><template v-if="modal==='DESIGNATE'"><label>填报人<select aria-label="填报人" v-model="person" required :disabled="busy"><option value="">请选择</option><option v-for="u in users" :value="u.id" :key="u.id">{{ u.name }} / {{ u.employeeNo }}</option></select></label><label>项目或事项<select aria-label="项目或事项" v-model="object" required :disabled="busy"><option value="">请选择</option><option v-for="w in objects" :value="w.id" :key="w.id">{{ w.name }}</option></select></label></template><template v-if="['TRANSFER','TRANSFER_CORRECTION','DESIGNATE'].includes(modal)"><label>新的审批人<select aria-label="新的审批人" v-model="approver" required :disabled="busy"><option value="">请选择在职且不是填报人的审批人</option><option v-for="u in users" :value="u.id" :key="u.id">{{ u.name }} / {{ u.employeeNo }}</option></select></label><label>指定依据<input v-model="basis" maxlength="500" required :disabled="busy" /></label></template><label v-if="modal==='RESOLVE'">结论<select aria-label="结论" v-model="outcome" :disabled="busy"><option value="CONFIRM_FACTS">确认填报属实</option><option value="NEEDS_CORRECTION">需要更正</option></select></label><label>事实说明 / 处理理由<textarea v-model="reason" rows="4" maxlength="2000" :required="modal!=='APPROVE'" :disabled="busy" /></label><p v-if="error" class="workflow-error" role="alert">{{ error }}</p><div class="workflow-actions"><button type="button" :disabled="busy" @click="modal=''">取消</button><button class="primary" :disabled="busy" type="submit">{{ busy?'正在处理…':'确认提交' }}</button></div></form></section></div></ModalShell>
</div></template>
