import { command, request } from '@worktime/api-client';
export interface Capabilities {canReadCosts:boolean;canClose:boolean;canUnlock:boolean;canPublish:boolean;projects:{id:string;code:string;name:string}[];users:{id:string;employeeNo:string;name:string}[];departments:{id:string;name:string}[]}
export interface Version {id:string;month:string;versionNo:number;cutoffAt:string;publishedAt:string;reason:string;previousVersionId:string|null}
export interface Report {kind:string;from:string;to:string;mode:string;generatedAt:string;versions:Version[];missingMonths:string[];summary:Record<string,unknown>;rows:Record<string,unknown>[];details:Record<string,unknown>[]}
export interface ExportJob {id:string;state:string;kind:string;createdAt:string;finishedAt:string|null;error:string|null;downloadUrl:string|null}
export interface ScopeInput {userId:string;date:string;workItemId:string|null;objectType:'TIME'|'ONSITE'|'BASE';recordId:string|null;actions:string[];reason:string}
export interface Scope extends ScopeInput {id:string;amendmentId:string;authorizedBy:string;authorizedAt:string;newAfterRecordId:string|null;active:boolean}
export interface Period {month:string;status:string;scheduledCloseAt:string;actualClosedAt:string|null;latestVersionId:string|null;versions:Version[];activeAmendment:{id:string;state:string;reason:string}|null;requests:{id:string;state:string;reason:string;requestedBy:string;createdAt:string;scopes:ScopeInput[]}[];scopes:Scope[];canClose:boolean;canUnlock:boolean;canPublish:boolean}
export const reporting={capabilities:()=>request<Capabilities>('/reports/capabilities'),report:(kind:string,query:Record<string,string>)=>request<Report>(`/reports/${kind}?${new URLSearchParams(Object.entries(query).filter(([,v])=>v))}`),exports:()=>request<ExportJob[]>('/exports'),export:(body:unknown)=>command<ExportJob>('/exports',body),download:(id:string)=>request<Blob>(`/exports/${id}/download`,{},'blob'),period:(month:string)=>request<Period>(`/periods/${month}`),close:(month:string)=>command<Version>(`/periods/${month}/close`),request:(month:string,reason:string,scopes:ScopeInput[])=>command(`/periods/${month}/requests`,{reason,scopes}),amend:(month:string,reason:string,requestId?:string)=>command(`/periods/${month}/amendments`,{reason,requestId}),scope:(month:string,id:string,body:ScopeInput)=>command(`/periods/${month}/amendments/${id}/scopes`,body),publish:(month:string,id:string,reason:string)=>command<Version>(`/periods/${month}/amendments/${id}/publish`,{reason}),amendmentDiff:(month:string,id:string)=>request<{fromVersionId:string;toVersionId:string|null;rows:Record<string,unknown>[]}>(`/periods/${month}/amendments/${id}/diff`),diff:(month:string,id:string)=>request<{fromVersionId:string;toVersionId:string|null;rows:Record<string,unknown>[]}>(`/periods/${month}/versions/${id}/diff`)};
