import { expect, test, type Page } from '@playwright/test';
import { today } from '../packages/api-client/src/index';
const date=today();
async function fixture(page:Page){const writes:{path:string;body:unknown;key:string|undefined}[]=[];let submits=0;
await page.route('**/api/v1/**',async route=>{const r=route.request(),path=new URL(r.url()).pathname.replace('/api/v1','');if(r.method()==='POST'&&!path.endsWith('preview'))writes.push({path,body:r.postData()?r.postDataJSON():null,key:r.headers()['idempotency-key']});
const me={id:'1',employeeNo:'98123',name:'验证员工',departmentName:'技术部',departmentId:'1',roles:['EMPLOYEE'],canManage:false};
const entry={id:'11',revisionId:'21',workItemId:'31',workItemName:'验证项目',kind:'WORK',hours:'8',minutes:480,content:'完成设备调试并核对交付记录',redReason:'',state:'APPROVED',editable:false,action:'REPORT',canRequestCorrection:true};
const day={date,version:1,baseMinutes:480,leaveMinutes:0,requiredMinutes:480,isWorkday:true,enrolled:true,editable:true,periodStatus:'OPEN',entries:[entry,{...entry,id:'12',revisionId:'22',action:'CANCEL',hours:'0',minutes:0,state:'DRAFT',editable:true}],onsite:null,totalMinutes:480,actualMinutes:480,idleMinutes:0,validation:{ready:true,errors:[],warnings:[]}};
if(path==='/auth/status')return route.fulfill({json:{mode:'local',localLoginEnabled:true,ssoConfigured:false}});if(path==='/me')return route.fulfill({json:me});if(path==='/auth/csrf')return route.fulfill({json:{headerName:'X-CSRF-TOKEN',token:'fixture'}});if(path==='/reports/capabilities')return route.fulfill({json:{canReadCosts:false,projects:[],users:[],departments:[]}});if(path==='/catalog')return route.fulfill({json:{departments:[],workItems:[{id:'31',name:'验证项目',type:'PROJECT'}]}});
if(path.startsWith('/days/'))return route.fulfill({json:r.method()==='PUT'?day:{...day,date:path.split('/').pop()}});
if(path.endsWith('/preview'))return route.fulfill({json:{weekStart:date,days:[{date,workReady:true,onsiteReady:false,errors:[],warnings:['仅取消版本待提交'],workItems:[{revisionId:'22',recordId:'12',workItemName:'验证项目',kind:'CANCEL',hours:'0',approverName:'项目经理',routeReason:'项目负责人'}],onsite:null}]}});
if(path.endsWith('/submit')){submits++;if(submits===1)return route.fulfill({status:503,json:{code:'TEMPORARY',message:'提交结果未知，请重试同一操作'}});return route.fulfill({json:{succeeded:[],failed:[{id:null,kind:'DAY',date,packageId:null,code:'PERIOD_LOCKED',message:'月份已封账，不能提交'}],unchanged:[]}});}
if(path.startsWith('/weeks/'))return route.fulfill({json:{weekStart:date,days:[day]}});
if(path==='/approval-packages/1')return route.fulfill({json:{package:{id:'1',userName:'验证员工',employeeNo:'98123',workItemName:'验证项目',weekStart:date,approverName:'项目经理',routeReason:'项目负责人',approvalDeadline:'2026-09-09T10:00:00Z',version:1,canDecide:true,pendingCount:1},otherWorkMinutes:0,correctionRequests:[],disputes:[],items:[{...entry,id:'101',kind:'TIME',recordId:'11',canDecide:true,canApprove:false,canReject:true,state:'PENDING',current:true,disputeOpen:true,canRequestCorrection:false,canDispute:false,handledName:null}]}});
if(path==='/approval-packages/1/decide')return route.fulfill({status:409,json:{code:'VERSION_CONFLICT',message:'审批包已变化，请刷新后核对'}});
return route.fulfill({json:[]});});return writes;}

test('取消草稿不作为 0 小时普通工时编辑；周提交失败保留真实结果并复用不确定请求键',async({page})=>{const writes=await fixture(page);page.on('dialog',dialog=>dialog.accept());await page.goto('http://127.0.0.1:5175/admin/time');await expect(page.getByText('此日期有取消申报版本，已从工时合计排除。请预览本周送审完成取消审批。')).toBeVisible();await expect(page.getByLabel('记录 2 小时数')).toHaveCount(0);await page.getByRole('button',{name:'预览本周送审',exact:true}).click();const modal=page.getByRole('dialog',{name:'本周送审预览'});await expect(modal.getByText(/验证项目 · 取消申报/)).toBeVisible();await modal.getByRole('button',{name:'提交符合条件的记录'}).click();await expect(modal.getByText('提交结果未知，请重试同一操作')).toBeVisible();await modal.getByRole('button',{name:'提交符合条件的记录'}).click();await expect(modal.getByText(/成功 0 项 · 失败 1 项/)).toBeVisible();await expect(modal.getByText(/月份已封账，不能提交/)).toBeVisible();const commands=writes.filter(w=>w.path.endsWith('/submit'));expect(commands).toHaveLength(2);expect(commands[0].key).toBeTruthy();expect(commands[1].key).toBe(commands[0].key);});

test('H5 争议需更正项只能退回；409 保留处理理由且金额字段不出现',async({page})=>{await page.setViewportSize({width:390,height:844});await fixture(page);await page.goto('http://127.0.0.1:5174/h5/approvals/1');await page.getByLabel(/选择 .* 工时记录/).check();await expect(page.getByRole('button',{name:'通过所选 1 项'})).toBeDisabled();await page.getByRole('button',{name:'驳回所选',exact:true}).click();const dialog=page.getByRole('dialog',{name:'驳回所选记录'});await dialog.getByLabel('事实说明 / 处理理由').fill('协调结论需要补充事实说明后重新提交');await dialog.getByRole('button',{name:'确认提交'}).click();await expect(dialog.getByText('审批包已变化，请刷新后核对')).toBeVisible();await expect(dialog.getByLabel('事实说明 / 处理理由')).toHaveValue('协调结论需要补充事实说明后重新提交');await expect(page.getByText(/试算金额|确认金额/)).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});

test('人员批量预览后状态冲突保留方案，必须重新预览再应用',async({page})=>{await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/api/v1','');const users=[{id:'1',employeeNo:'98123',name:'甲员工',departmentId:'1',level:'MIDDLE',roles:['EMPLOYEE'],status:'ACTIVE'},{id:'2',employeeNo:'XX12345',name:'乙员工',departmentId:'1',level:'MIDDLE',roles:['EMPLOYEE'],status:'ACTIVE'}];if(path==='/auth/status')return route.fulfill({json:{mode:'local',localLoginEnabled:true,ssoConfigured:false}});if(path==='/me')return route.fulfill({json:{id:'9',employeeNo:'00123',name:'管理员',departmentName:'技术部',roles:['ADMIN'],canManage:true}});if(path==='/auth/csrf')return route.fulfill({json:{headerName:'X-CSRF-TOKEN',token:'fixture'}});if(path==='/reports/capabilities')return route.fulfill({json:{canReadCosts:true}});if(path==='/master/users')return route.fulfill({json:users});if(path==='/master/departments')return route.fulfill({json:[{id:'1',code:'D',name:'技术部',status:'ACTIVE'}]});if(path==='/master/users/batch/preview')return route.fulfill({json:{expectedFingerprint:'verified-v1',canApply:true,errors:[],rows:users.map(u=>({userId:u.id,employeeNo:u.employeeNo,name:u.name,fromDepartmentName:'技术部',toDepartmentName:'技术部',fromLevel:'MIDDLE',toLevel:'SENIOR',affectedDayCount:0,approvedRevisionCount:0}))}});if(path==='/master/users/batch/apply'){expect(route.request().postDataJSON().expectedFingerprint).toBe('verified-v1');return route.fulfill({status:409,json:{code:'BATCH_CHANGED',message:'人员范围已变化，请重新预览'}});}return route.fulfill({json:[]});});await page.goto('http://127.0.0.1:5175/admin/people');await page.getByRole('row').filter({hasText:'甲员工'}).locator('.el-checkbox').click();await page.getByRole('row').filter({hasText:'乙员工'}).locator('.el-checkbox').click();await page.getByRole('button',{name:'批量调整部门 / 职级'}).click();const d=page.getByRole('dialog',{name:'批量人员方案'});await d.getByLabel('目标职级',{exact:true}).selectOption('SENIOR');await d.getByLabel('业务核实理由').fill('核实两名员工的下一阶段职级调整');await d.getByRole('button',{name:'预览方案'}).click();await expect(d.getByRole('button',{name:'确认应用整批'})).toBeEnabled();await d.getByRole('button',{name:'确认应用整批'}).click();await expect(d.getByText('人员范围已变化，请重新预览')).toBeVisible();await expect(d.getByLabel('业务核实理由')).toHaveValue('核实两名员工的下一阶段职级调整');await expect(d.getByRole('button',{name:'确认应用整批'})).toBeDisabled();});

test('部门事项入口仅取精简选项，固定本地非项目；越权失败保留输入',async({page})=>{const reads:string[]=[];await page.route('**/api/v1/**',async route=>{const r=route.request(),path=new URL(r.url()).pathname.replace('/api/v1','');reads.push(path);if(path==='/auth/status')return route.fulfill({json:{mode:'local',localLoginEnabled:true,ssoConfigured:false}});if(path==='/me')return route.fulfill({json:{id:'3',employeeNo:'ZD23412',name:'部门负责人',departmentName:'技术部',roles:['DEPARTMENT_MANAGER'],canManage:false}});if(path==='/auth/csrf')return route.fulfill({json:{headerName:'X-CSRF-TOKEN',token:'fixture'}});if(path==='/reports/capabilities')return route.fulfill({json:{canReadCosts:true}});if(path==='/master/non-project-options')return route.fulfill({json:{departments:[{id:'1',name:'技术部'}],approvers:[{id:'3',name:'部门负责人'}],canManageProjects:false}});if(path==='/master/work-items'&&r.method()==='POST'){const body=r.postDataJSON();expect(body.type).toBe('NON_PROJECT');expect(body.source).toBe('LOCAL');return route.fulfill({status:403,json:{code:'SCOPE_CHANGED',message:'部门授权已撤销，请重新核实权限'}});}return route.fulfill({json:[]});});await page.goto('http://127.0.0.1:5175/admin/department-items');await page.getByRole('button',{name:'新增归集对象'}).click();const d=page.getByRole('dialog',{name:'新增归集对象'});await d.getByLabel('对象编码').fill('LOCAL-NP');await d.getByLabel('对象名称').fill('部门知识沉淀');await expect(d.locator('#master-type')).toBeDisabled();await d.getByRole('combobox',{name:'主责部门'}).click();await page.getByRole('option',{name:'技术部',exact:true}).click();await d.getByRole('button',{name:'保存归集对象'}).click();await expect(d.getByText('部门授权已撤销，请重新核实权限')).toBeVisible();await expect(d.getByLabel('对象名称')).toHaveValue('部门知识沉淀');expect(reads).not.toContain('/master/users');expect(reads).not.toContain('/master/departments');});
